# -*- coding: utf-8 -*-
"""Ai_task_1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOvgwoJEtyIOyaPI7oA9G6ZRhCJX3RSY
"""

import math as m
c=2
d=3
mod = d%c
pow = m.pow (c,d) #2^3
pow2 = c**d # c^d
fdiv = d//c # floor or intiger divison

print(f"Mod :{mod}, Powe_func : {pow},Powe_func : {pow2} and floor div: {fdiv}")

a= 10
b=5
sum = a+b
sub = a-b
prod =a*b
div = a/b
print("Sum :" , sum)
print (f"Sum :{sum}, Sub: {sub}, Product: {prod}, division: {div}" )

#absolute and round
num1 =-7.6
num2 = 3.6
print("abs: ",abs(num1))
print("round num1 : ", round(num1))
print("round num2 : ", round(num2))

#sqrt , factorial , trigonometric value

sqrt =m.sqrt(16)
fact = m.factorial(5)
sin_val = m.sin(m.radians(30))

print(f"sqrt : {sqrt},factorial :{fact}, sin30 : {sin_val} ")

#repeat string
str1 = "Hello " *3
print(str1)

#concate
str2 ="Hello"
str3 ="World"
text = str2 +" "+str3
print(text)

text2 = str2.upper() + "  we "+str3.lower()
print(text2)
print(len(text2))

#find string
indx = text2.find("world")
print("index : ", indx)

#Slicing
substr = text2[3:8]
print(substr)

#tokensize
word= text2.split(" ") # .split(",") .split(";")
print(word)
print(len(word))